[package]
name = "sweet"
version = "0.1.0"
edition = "2018"

[features]
exclude_entrypoint = []

[dependencies]
solana-program = "1.7.11"
solana-program-test = "1.7.11"
byteorder = "1.4.3"
thiserror = "1.0"
borsh = "0.9.1"
borsh-derive = "0.9.0"


[lib]
name = "sweet"
crate-type = ["cdylib", "lib"]